print('{:=^20}'.format('Desafio 007'))
print('Enunciado: \nUm programa que lê duas notas de um aluno, calcula e motra a sua média')
n1 = int(input('Primeira nota: '))
n2 = int(input('Segunda nota: '))
print('Média: ', (n1+n2)/2)
