nome = str(input('Digite um nome completo: '))
print('Nome {} em:'.format(nome))
print('Maiúsculas: {}'.format(nome.upper()))
print('Minúsculas: {}'.format(nome.lower()))
nome2 = nome.split()
print('Possui {} letras'.format(len(''.join(nome2))))
print('O primeiro nome é {}'.format(nome2[0]))
print('A primeira letra é {}'.format(nome2[0][0]))
print('O segundo nome é: {}'.format(nome2[1]))
print('A primeira letra do segundo nome é: {}'.format(nome2[1][0]))
